User.create!(username: 'planarian', fname: 'jay', lname: 'davis', email: 'abc@abc.com', password: 'abc')
User.create!(username: 'nematode', fname: 'bill', lname: 'barnett', email: 'cbs@cbs.com', password: 'abc')
User.create!(username: 'platypus', fname: 'shelly', lname: 'smith', email: 'nbc@nb.com', password: 'abc')

Office.create!(name: 'Dr. Robert Soderquist', addr1: '3600 Broadway', city: "New York", state: "NY", zip: "10026")
Office.create!(name: 'Dr. Angus McNab', addr1: '703 W. Main St.', city: "New York", state: "NY", zip: "10038")
Office.create!(name: 'Dr. Rebecca Agarwhal', addr1: '42 N. Hamilton Blvd', city: "New York", state: "NY", zip: "10048")

Review.create!(rating: 5, title: "This place is great!", content: "GREAT GREAT GREAT!!", user_id: 1, office_id: 1)
Review.create!(rating: 3, title: "This place is average!", content: "AVERAGE AVERAGE AVERAGE!!", user_id: 2, office_id: 2)
Review.create!(rating: 2, title: "This place is really not great!", content: "NOT GREAT NOT GREAT NOT GREAT!!", user_id: 1, office_id: 3)
Review.create!(rating: 2, title: "This place is bad!", content: "BAD BAD BAD!!", user_id: 3, office_id: 1)
Review.create!(rating: 1, title: "This place is awful!", content: "AWFUL AWFUL AWFUL!!", user_id: 1, office_id: 2)

Vote.create!(verdict: 1, user_id: 1, review_id: 1)
Vote.create!(verdict: 1, user_id: 1, review_id: 2)
Vote.create!(verdict: -1, user_id: 1, review_id: 3)
Vote.create!(verdict: 1, user_id: 1, review_id: 4)
Vote.create!(verdict: 1, user_id: 1, review_id: 5)
Vote.create!(verdict: -1, user_id: 2, review_id: 1)
Vote.create!(verdict: 1, user_id: 2, review_id: 2)
Vote.create!(verdict: -1, user_id: 2, review_id: 3)
Vote.create!(verdict: -1, user_id: 2, review_id: 4)
Vote.create!(verdict: 1, user_id: 2, review_id: 5)
Vote.create!(verdict: -1, user_id: 3, review_id: 1)
Vote.create!(verdict: 1, user_id: 3, review_id: 2)
Vote.create!(verdict: -1, user_id: 3, review_id: 3)
Vote.create!(verdict: -1, user_id: 3, review_id: 4)
Vote.create!(verdict: 1, user_id: 3, review_id: 5)
